vim.lsp.set_log_level("trace")

require('plugins')
require('base')
require('pluginrc.lspconfig')
require('pluginrc.nvim-cmp')
require('pluginrc.nvim-treesitter')
require('pluginrc.telescope')
require('pluginrc.statusline')
require('pluginrc.indent-blankline')
require('pluginrc.explorer')
require('pluginrc.formatter')
require('pluginrc.comment')
require('pluginrc.nvim-toggleterm')
require('pluginrc.nvim-autopairs')
require('pluginrc.theme')
require('pluginrc.lspsignature')
-- require('pluginrc.vimtex')
