vim.lsp.set_log_level("trace")

require('plugins')
require('base')
require('pluginrc.lsp')
require('pluginrc.nvim-treesitter')
require('pluginrc.telescope')
require('pluginrc.gen_tags')
require('pluginrc.statusline')
require('pluginrc.indent-blankline')
-- require('pluginrc.nvim-tree')
require('pluginrc.formatter')
require('pluginrc.nvim-toggleterm')
require('pluginrc.nvim-autopairs')
require('pluginrc.theme')
